project:
  type: website
  output-dir: docs
# Force index.qmd to render always first (first rendered document will be the quarto index file in docs)
# Force render just analysis folder, otherwise quarto will try to render any rmd or qmd in the project (like vignettes)
# Add any extra folders with qmd's that you would like to render also
  render:
    - analysis/index.qmd
    - analysis

website:
  title: "{{cookiecutter.project_name}}"
  navbar:
    background: light
    title: "{{cookiecutter.project_name}}"
    left:
      - text: Home
        href: index.qmd

format:
  html:
    author: "{{cookiecutter.author_name}}"
    toc: true
    code-fold: true
    code-tools: true
    code-overflow: scroll
    fig-align: center
    fig-width: 6
    fig-height: 5
    fig-format: png
    smooth-scroll: true
    theme: 
      light: [cosmo, theme.scss]
    df-print: paged
    css: styles.css
    number-sections: true
    number-depth: 3
    date: today

execute:
  freeze: auto
  echo: true
  error: false
  warning: false
  message: false

editor: source
